version: "3.5"

volumes:
  grafanadata: {}
  vmdata: {}

services:
  telegraf:
    image: telegraf:latest 
    volumes:
      - ./etc/telegraf/agent.yml:/etc/agent.yml:ro
    command:
      - --config=/etc/agent.yml
    restart: always

  vmagent:
    image: victoriametrics/vmagent
    volumes:
      - ./etc/vmagent/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '-promscrape.config=/etc/prometheus/prometheus.yml'
      - '-remoteWrite.url=http://victoriametrics:8428/api/v1/write'

  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
    volumes:
      - vmdata:/storage

  self_cadvisor:
    image: google/cadvisor:latest 
    privileged: true
    ports:
      - target: 8080
        published: 58080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafanadata:/var/lib/grafana
      - ./etc/grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
      - ./etc/grafana/plugins/:/var/lib/grafana/plugins/