global:
  scrape_interval: 10s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'self-monitor'
    metrics_path: /metrics
    static_configs:
      - targets: [ "self_cadvisor:8080" ]
